### ISSUE TITLE
When do you plan to release the source code?

### ISSUE THREAD

**Issue by tianmingdu** [kelisiya/TIMI-Net#1]
It's an amazing work. I've tried some images/trimaps in your evaluation page and the demo results looks great. When do you plan to release the training code and models? Is it possible to release the Human-2K datasets as well?

**Comment by kelisiya** [comment]
Thanks for paying attention to our work, we are currently preparing camera ready, and  planning to advance the open source of this work including models and datasets.

> It's an amazing work. I've tried some images/trimaps in your evaluation page and the demo results looks great. When do you plan to release the training code and models? Is it possible to release the Human-2K datasets as well?

Thanks for paying attention to our work, we are currently preparing camera ready, and  planning to advance the open source of this work including models and datasets.

**Comment by kelisiya** [comment]
> It's an amazing work. I've tried some images/trimaps in your evaluation page and the demo results looks great. When do you plan to release the training code and models? Is it possible to release the Human-2K datasets as well?

Thanks for paying attention to our work, we are currently preparing camera ready, and  planning to advance the open source of this work including models and datasets.

**Comment by Serge-weihao** [comment]
@kelisiya Will your group release your Distinctions-646 datasets? We did need Distinctions-646 for research.

**Comment by yuhaoliu7456** [comment]
> @kelisiya Will your group release your Distinctions-646 datasets? We did need Distinctions-646 for research.

Hi, please send us an email to retrieve the Distinctions-646. yuhaoliu7456@gmail.com. Thanks
