### ISSUE TITLE
Problem of dataset downloading

### ISSUE THREAD

**Issue by maoyj2333** [kelisiya/TIMI-Net#10]
Hi, thank you for the enlightening work. 
When I am trying to download the human2k dataset at first time, it worked. So I copied the onedrive link into the server and use the wget command to download it, but the downloaded file cannot be unzipped due to some coruption maybe.
The second time I access the onedrive link in the github page, it keeps giving me the error results:
![image](https://github.com/kelisiya/TIMI-Net/assets/73008189/5574620f-7448-4158-a987-cd446c455477)

I am wondering whether it is because I have done some damage to the link.
Great thanks

**Comment by kelisiya** [comment]
> Hi, thank you for the enlightening work. When I am trying to download the human2k dataset at first time, it worked. So I copied the onedrive link into the server and use the wget command to download it, but the downloaded file cannot be unzipped due to some coruption maybe. The second time I access the onedrive link in the github page, it keeps giving me the error results: ![image](https://user-images.githubusercontent.com/73008189/250502230-5574620f-7448-4158-a987-cd446c455477.png)
> 
> I am wondering whether it is because I have done some damage to the link. Great thanks

This is because my OneDrive is invalid, and it will take some time to restore it. I created a Baidu disk address and hope it will help you. At the same time, if you need more support, you can email me your wechat . 

Adress : https://pan.baidu.com/s/10ebBi1Ffz791hIPUbNzQcg?pwd=85r6

**Comment by maoyj2333** [comment]
great thanks, I will first try the baidu disk

**Comment by maoyj2333** [comment]
Hello, there indeed exists a strange problem
![image](https://github.com/kelisiya/TIMI-Net/assets/73008189/dbf699e3-dd72-4487-9259-44ffda3c2c91)
It seems like the file was corrupte. The error is the same as I first download and unzip it.

**Comment by ZC0102-shu** [comment]
same here, some files broken.

**Comment by kelisiya** [comment]
> same here, some files broken.

Sorry for not replying for so long，I've been busy recently，But I plan to get this out of the way this week, and then I'll let you guys know again to download . QAQ

**Comment by ZC0102-shu** [comment]
> > same here, some files broken.
> 
> Sorry for not replying for so long，I've been busy recently，But I plan to get this out of the way this week, and then I'll let you guys know again to download . QAQ

All right , we'll wait for you. QAQ

**Comment by FishHe** [comment]
the same.

**Comment by kelisiya** [comment]
> the same.

Sorry for the late reply, I'm already re-uploading the dataset due to masOS miscompression causing trouble for everyone and will re-publish it soon

**Comment by kelisiya** [comment]
Send to all:  https://pan.baidu.com/s/16Q92kgjrERdSp7bI85GQ0Q?pwd=t88g  , code : t88g

**Comment by kelisiya** [comment]
> > > same here, some files broken.
> > 
> > 
> > Sorry for not replying for so long，I've been busy recently，But I plan to get this out of the way this week, and then I'll let you guys know again to download . QAQ
> 
> All right , we'll wait for you. QAQ

hi , did you solve the problem ?
