### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by SysDevHayes** [kelisiya/TIMI-Net#2]
Firstly, congrats to the team for the interesting results. I have tested your model and get some interesting results. Since I really want to benchmark the model with a little bit more challenging dataset, I used the training code from [GCA-Matting](https://github.com/Yaoyi-Li/GCA-Matting) (thanks to Yaoyi-Li for his very clean code). However, I got the following error, which is not clearly stated where the problem came from:

> RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

Can you please give me some guidance to fix this? Thank you so much.

**Comment by SysDevHayes** [comment]
Quick update:
I added `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel` and it seems to work. But it caused OOM. I have 2 RTX 3090s, I don't think the training resources should be that expensive. Even I tried the batch size of 2. Can you please help me to fix this issue? Thank you so much.

**Comment by kelisiya** [comment]
Can you provide more training parameters? The input in the paper is 512*512 , your problem may be related to wolrd size or dataloader num workers. At the same time , you can try to use  DataParallel instead of DistributedDataParallel.

**Comment by SysDevHayes** [comment]
Ah, found the problem. After an hour of debugging, turned out the problem came from my data loader. You pointed right away to the problem. Thank you so much @kelisiya
