### ISSUE TITLE
Could you open the dataset(Human-2k)?

### ISSUE THREAD

**Issue by kings-rgb** [kelisiya/TIMI-Net#3]

**Comment by kelisiya** [comment]
Of course, our data will be open in these days~

**Comment by kings-rgb** [comment]
Hi, since then it's been two weeks. We want to test our model in your dataset and our work is about image matting academic research. If the result is good, we will open the paper. So, could you open the link about Human-2k recently?

**Comment by kelisiya** [comment]
> Hi, since then it's been two weeks. We want to test our model in your dataset and our work is about image matting academic research. If the result is good, we will open the paper. So, could you open the link about Human-2k recently?

Sorry, I’ve been too busy recently. The data has been checked and is being uploaded. If necessary, you can send an email to jxie@picup.ai and I will send it to you via Baidu Download Link.
