### ISSUE TITLE
request for the dataset

### ISSUE THREAD

**Issue by WangChyanhassth-2say** [kelisiya/TIMI-Net#4]
Hi,
I remember that you guys were the author of the paper hattmatting in cvpr2020 right? That's an awesome work !
And I would like to ask you to share the dataset Distinctions-646 to me, which I may need to use in training my models.
Just for academic research purpose, here's my email address 1812480217@st.usst.edu.cn .
Thx a lot!

**Comment by kelisiya** [comment]
> Hi, I remember that you guys were the author of the paper hattmatting in cvpr2020 right? That's an awesome work ! And I would like to ask you to share the dataset Distinctions-646 to me, which I may need to use in training my models. Just for academic research purpose, here's my email address [1812480217@st.usst.edu.cn](mailto:1812480217@st.usst.edu.cn) . Thx a lot!

Please send  email to yuhaoliu7456@gmail.com~

**Comment by WangChyanhassth-2say** [comment]
I have already sent the email, could you plz give a little notice to the maintainer?
Very thank to you!

**Comment by WangChyanhassth-2say** [comment]
> > Hi, I remember that you guys were the author of the paper hattmatting in cvpr2020 right? That's an awesome work ! And I would like to ask you to share the dataset Distinctions-646 to me, which I may need to use in training my models. Just for academic research purpose, here's my email address [1812480217@st.usst.edu.cn](mailto:1812480217@st.usst.edu.cn) . Thx a lot!
> 
> Please send email to [yuhaoliu7456@gmail.com](mailto:yuhaoliu7456@gmail.com)~

Hi,
since then it's been a week.
It may be vital to my academic research, help plz.

**Comment by yuhaoliu7456** [comment]
Sorry to reply to you late. Recently, I have been busy with other things. I will reply to you shortly

**Comment by yuhaoliu7456** [comment]
> I have already sent the email, could you plz give a little notice to the maintainer? Very thank to you!

Can you send me an email again, in case I send it to others by mistake?

**Comment by WangChyanhassth-2say** [comment]
> > I have already sent the email, could you plz give a little notice to the maintainer? Very thank to you!
> 
> Can you send me an email again, in case I send it to others by mistake?

THX!!! I just sent anothor email, very thanks to you!

**Comment by WangChyanhassth-2say** [comment]
> > I have already sent the email, could you plz give a little notice to the maintainer? Very thank to you!
> 
> Can you send me an email again, in case I send it to others by mistake?

Hi,
have you got the email named 'requests for the Dinstinctions-646 dataset' yet ?
I've sent it on 09:53 2021/11/1
And my edu email address is 1812480217@st.usst.edu.cn
plz don't wait any longer : (

**Comment by WangChyanhassth-2say** [comment]
> > I have already sent the email, could you plz give a little notice to the maintainer? Very thank to you!
> 
> Can you send me an email again, in case I send it to others by mistake?

I'm so sorry but, can you check your email and my requests may be in the junk box since I have been sent it multiple times.
Maybe you can directly send the dataset to my edu address 1812480217@st.usst.edu.cn?
