### ISSUE TITLE
Human Matting Dataset链接失效

### ISSUE THREAD

**Issue by Hun-ger** [kelisiya/TIMI-Net#5]
感谢作者分享。但是我在下载数据集的时候遇到了问题。
1. Human Matting Dataset 的one drive链接失效。
2. 百度云下载的文件解压出错。
希望能及时更新！感谢!

**Comment by kelisiya** [comment]
1.我将稍后更新链接
2.如果你使用的windows系统推荐使用7z进行解压



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月19日(周三) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [kelisiya/TIMI-Net] Human Matting Dataset链接失效 (Issue #5)




 
感谢作者分享。但是我在下载数据集的时候遇到了问题。
  
Human Matting Dataset 的one drive链接失效。 

百度云下载的文件解压出错。
 希望能及时更新！感谢! 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hun-ger** [comment]
非常感谢！
