### ISSUE TITLE
Link to the dataset is no longer available

### ISSUE THREAD

**Issue by Brothre23** [kelisiya/TIMI-Net#6]
Hi,

I found your work really amazing, and want to use your Human-2K dataset for my research on image matting, but the link is no longer available now, so can you please upload it again?

Also, I remember that HattMatting is also your work, and I would like to use the Distinctions-646 dataset, too. I've sent an mail to one of your team members months ago, but did not receive a reply. Is there any way I can get it?

Thanks.

**Comment by kelisiya** [comment]
> 

You can try Baidu Disk Download, and I will update the data to Onedrive later. Dis646 Please use the .edu mail to send information to the relevant author

**Comment by Brothre23** [comment]
Thanks a lot!
But I think the link to the Baidu Disk is the result produced by your method on the dataset, not the dataset itself?
If it is, then maybe I can just download the Baidu version.
Also, I've re-sent a mail to ask for the D646 dataset with my .edu mail, and hope I can get a reply soon!

**Comment by kelisiya** [comment]
> Thanks a lot! But I think the link to the Baidu Disk is the result produced by your method on the dataset, not the dataset itself? If it is, then maybe I can just download the Baidu version. Also, I've re-sent a mail to ask for the D646 dataset with my .edu mail, and hope I can get a reply soon!

https://pan.baidu.com/s/1v_YrSYQGkdW2yeKTi1_5CQ (fvim) ， HattMatting isn't my work, so I'm not sure you'll get a prompt response
