### ISSUE TITLE
Invalid OneDrive link

### ISSUE THREAD

**Issue by qjadud1994** [kelisiya/TIMI-Net#7]
Thank you for sharing your great work and dataset.

I tried to download the Human-2K dataset using the [Onedrive link](https://1drv.ms/u/s!Av_a_mizgnnPhg_aaV_-Hdegm1K6?e=ReH9Pu), but the link seems to be wrong :(

Could you share a valid Onedrive link for me?

I cannot access the Baidu link, and the Googledrive is one of altenatives.

Thanks.

**Comment by kelisiya** [comment]
> 

I'm sorry . you can use "https://1drv.ms/u/s!Av_a_mizgnnPhhCOhfnxQrn9J2Le?e=15J3bS" , I will update it in my github .

**Comment by qjadud1994** [comment]
Thank you for the fast reply :)

Now, I can download the dataset.

Thanks.

**Comment by qjadud1994** [comment]
@kelisiya  Sorry for bother you :(

I checked the Human-2K dataset, but the `training_bg_names.txt` is empty.

Could you share the `training_bg_names.txt` again?

**Comment by kelisiya** [comment]
> @kelisiya Sorry for bother you :(
> 
> I checked the Human-2K dataset, but the `training_bg_names.txt` is empty.
> 
> Could you share the `training_bg_names.txt` again?

we use mscoco dataset  to  generate background list , you can download mscoco to get training list . And animal matting provide a HR bg dataset named BG2K the you can compose HR image .

**Comment by qjadud1994** [comment]
@kelisiya 
I have a concern about the matting data composition.
For human matting, you generate a synthetic human matting images by blending GT alpha and BG image.

However, some BG images from COCO or VOC contain 'person' and this person remains unlabeled in the synthetic matting data.
My concern is that the person in BG image will be a false-negative sample for human matting, hurting stable learning.
How do you think about this? Do you use other technique to address this?
