### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by honey-zhao** [kelisiya/TIMI-Net#9]
Dear author, when will the train.py be released approximately? Your algorithm is important to my research, thank you very much for your work and I look forward to hearing from you!

**Comment by kelisiya** [comment]
> Dear author, when will the train.py be released approximately? Your algorithm is important to my research, thank you very much for your work and I look forward to hearing from you!

We use GCA matting  training code to train TIMI-net .

**Comment by honey-zhao** [comment]
> > Dear author, when will the train.py be released approximately? Your algorithm is important to my research, thank you very much for your work and I look forward to hearing from you!
> 
> We use GCA matting training code to train TIMI-net .

OK. Thank you! I have another question, if I use your network to train my own dataset, after training, if I want to do image matting, do I still need trimap for my input?

**Comment by kelisiya** [comment]
> 

Yes,TIMI-net is a trimap-based method to mining tripartite information . We will also introduce the exploration information mining mechanism into the work of trimap free in the future

**Comment by honey-zhao** [comment]
> > 
> 
> 是的，TIMI-net是一种基于三图的三方信息挖掘方法。未来我们还将把探索信息挖掘机制引入到无三图的工作中。

OK, Thank you very much!
